baseURL = "http://hugovantighem.github.io/"
languageCode = "fr-fr"
title = "Hugo Vantighem"

theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true